-- MySQL Script generated by MySQL Workbench
-- Fri Apr  7 21:34:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sedb` ;

-- -----------------------------------------------------
-- Schema sedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sedb` DEFAULT CHARACTER SET utf8 ;
USE `sedb` ;

-- -----------------------------------------------------
-- Table `sedb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`user` ;

CREATE TABLE IF NOT EXISTS `sedb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(16) NOT NULL,
  `user_psw` VARCHAR(16) NOT NULL,
  `user_realname` VARCHAR(16) NOT NULL,
  `user_icid` VARCHAR(18) NOT NULL,
  `user_school` VARCHAR(16) NULL,
  `user_sid` VARCHAR(16) NULL,
  `user_gender` INT NOT NULL,
  `user_phone` VARCHAR(16) NOT NULL,
  `user_image` VARCHAR(128) NOT NULL,
  `user_add1` VARCHAR(128) NOT NULL,
  `user_add2` VARCHAR(128) NULL,
  `user_add3` VARCHAR(128) NULL,
  `user_ifsell` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sedb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`chat` ;

CREATE TABLE IF NOT EXISTS `sedb`.`chat` (
  `chat_time` DATETIME NOT NULL,
  `chat_content` VARCHAR(100) NOT NULL,
  `chat_sender` INT NOT NULL,
  `chat_receiver` INT NOT NULL,
  PRIMARY KEY (`chat_time`, `chat_sender`, `chat_receiver`),
  CONSTRAINT `sender`
    FOREIGN KEY (`chat_sender`)
    REFERENCES `sedb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `receiver`
    FOREIGN KEY (`chat_receiver`)
    REFERENCES `sedb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`session` ;

CREATE TABLE IF NOT EXISTS `sedb`.`session` (
  `chat_sender` INT NOT NULL,
  `chat_receiver` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  PRIMARY KEY (`chat_sender`, `chat_receiver`),
  CONSTRAINT `sender_1`
    FOREIGN KEY (`chat_sender`)
    REFERENCES `sedb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `receiver_1`
    FOREIGN KEY (`chat_receiver`)
    REFERENCES `sedb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`commodity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`commodity` ;

CREATE TABLE IF NOT EXISTS `sedb`.`commodity` (
  `com_id` INT NOT NULL AUTO_INCREMENT,
  `com_publisher` INT NOT NULL,
  `com_name` VARCHAR(64) NOT NULL,
  `com_des` VARCHAR(512) NOT NULL,
  `com_cat` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`com_id`),
  CONSTRAINT `publisher`
    FOREIGN KEY (`com_publisher`)
    REFERENCES `sedb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`item` ;

CREATE TABLE IF NOT EXISTS `sedb`.`item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NOT NULL,
  `item_name` VARCHAR(64) NOT NULL,
  `item_left` INT NOT NULL,
  `item_price` FLOAT NOT NULL,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `sedb`.`commodity` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`cart` ;

CREATE TABLE IF NOT EXISTS `sedb`.`cart` (
  `cart_user` INT NOT NULL,
  `cart_item` INT NOT NULL,
  `cart_num` INT NOT NULL,
  CONSTRAINT `user`
    FOREIGN KEY (`cart_user`)
    REFERENCES `sedb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item`
    FOREIGN KEY (`cart_item`)
    REFERENCES `sedb`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`favorites` ;

CREATE TABLE IF NOT EXISTS `sedb`.`favorites` (
  `fav_user` INT NOT NULL,
  `fav_item` INT NULL,
  CONSTRAINT `user_1`
    FOREIGN KEY (`fav_user`)
    REFERENCES `sedb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_1`
    FOREIGN KEY (`fav_item`)
    REFERENCES `sedb`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`detail` ;

CREATE TABLE IF NOT EXISTS `sedb`.`detail` (
  `father_id` INT NOT NULL,
  `detail_image` VARCHAR(128) NOT NULL,
  CONSTRAINT `commodity`
    FOREIGN KEY (`father_id`)
    REFERENCES `sedb`.`commodity` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`preview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`preview` ;

CREATE TABLE IF NOT EXISTS `sedb`.`preview` (
  `father_id` INT NOT NULL,
  `preview_image` VARCHAR(128) NULL,
  CONSTRAINT `father`
    FOREIGN KEY (`father_id`)
    REFERENCES `sedb`.`commodity` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`order` ;

CREATE TABLE IF NOT EXISTS `sedb`.`order` (
  `order_id` INT NOT NULL,
  `order_buyer` INT NOT NULL,
  `order_seller` INT NOT NULL,
  `order_num` INT NOT NULL,
  `order_price` INT NOT NULL,
  `order_address` VARCHAR(128) NOT NULL,
  `order_item` INT NOT NULL,
  `order_state` ENUM('发货', '确认收货', '退货') NOT NULL,
  `order_time` DATETIME NOT NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `buyer`
    FOREIGN KEY (`order_buyer`)
    REFERENCES `sedb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seller`
    FOREIGN KEY (`order_seller`)
    REFERENCES `sedb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_2`
    FOREIGN KEY (`order_item`)
    REFERENCES `sedb`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`comment` ;

CREATE TABLE IF NOT EXISTS `sedb`.`comment` (
  `com_id` INT NOT NULL,
  `com_content` VARCHAR(128) NULL,
  `com_time` DATETIME NULL,
  `com_choose` ENUM('好评', '中评', '差评') NULL,
  `commentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`com_id`),
  CONSTRAINT `order`
    FOREIGN KEY (`com_id`)
    REFERENCES `sedb`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedb`.`comment_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedb`.`comment_picture` ;

CREATE TABLE IF NOT EXISTS `sedb`.`comment_picture` (
  `father_id` INT NOT NULL,
  `comment_image` VARCHAR(128) NULL,
  CONSTRAINT `comment`
    FOREIGN KEY (`father_id`)
    REFERENCES `sedb`.`comment` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
