-- MySQL Script generated by MySQL Workbench
-- Fri Apr  7 21:34:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(16) NOT NULL,
  `user_psw` VARCHAR(16) NOT NULL,
  `user_realname` VARCHAR(16) NOT NULL,
  `user_icid` VARCHAR(18) NOT NULL,
  `user_school` VARCHAR(16) NULL,
  `user_sid` VARCHAR(16) NULL,
  `user_gender` ENUM('男', '女', '其他') NOT NULL,
  `user_phone` VARCHAR(16) NOT NULL,
  `user_image` VARCHAR(128) NOT NULL,
  `user_add1` VARCHAR(128) NOT NULL,
  `user_add2` VARCHAR(128) NULL,
  `user_add3` VARCHAR(128) NULL,
  `user_ifsell` TINYINT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  UNIQUE INDEX `user_icid_UNIQUE` (`user_icid` ASC) VISIBLE,
  UNIQUE INDEX `user_phone_UNIQUE` (`user_phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chat` (
  `chat_id` INT NOT NULL,
  `chat_time` DATETIME NOT NULL,
  `chat_content` VARCHAR(100) NOT NULL,
  `chat_sender` INT NOT NULL,
  `chat_receiver` INT NOT NULL,
  PRIMARY KEY (`chat_id`),
  INDEX `receiver_idx` (`chat_receiver` ASC) VISIBLE,
  INDEX `sender_idx` (`chat_sender` ASC) VISIBLE,
  CONSTRAINT `sender`
    FOREIGN KEY (`chat_sender`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `receiver`
    FOREIGN KEY (`chat_receiver`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commodity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commodity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commodity` (
  `com_id` INT NOT NULL,
  `com_publisher` INT NOT NULL,
  `com_name` VARCHAR(45) NOT NULL,
  `com_des` VARCHAR(256) NOT NULL,
  `com_cat` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`com_id`),
  UNIQUE INDEX `com_id_UNIQUE` (`com_id` ASC) VISIBLE,
  INDEX `publisher_idx` (`com_publisher` ASC) VISIBLE,
  CONSTRAINT `publisher`
    FOREIGN KEY (`com_publisher`)
    REFERENCES `mydb`.`user` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `item_id` INT NOT NULL,
  `parent_id` INT NOT NULL,
  `item_name` VARCHAR(45) NOT NULL,
  `item_left` INT NOT NULL,
  `item_price` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  INDEX `parent_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `mydb`.`commodity` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `cart_user` INT NOT NULL,
  `cart_item` INT NOT NULL,
  `cart_num` INT NOT NULL,
  INDEX `user_idx` (`cart_user` ASC) VISIBLE,
  INDEX `item_idx` (`cart_item` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`cart_user`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item`
    FOREIGN KEY (`cart_item`)
    REFERENCES `mydb`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`favorites` ;

CREATE TABLE IF NOT EXISTS `mydb`.`favorites` (
  `fav_user` INT NOT NULL,
  `fav_item` INT NULL,
  INDEX `user_idx` (`fav_user` ASC) VISIBLE,
  INDEX `item_idx` (`fav_item` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`fav_user`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item`
    FOREIGN KEY (`fav_item`)
    REFERENCES `mydb`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detail` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detail` (
  `father_id` INT NOT NULL,
  `detail_image` VARCHAR(128) NOT NULL,
  INDEX `commodity_idx` (`father_id` ASC) VISIBLE,
  CONSTRAINT `commodity`
    FOREIGN KEY (`father_id`)
    REFERENCES `mydb`.`commodity` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`preview` ;

CREATE TABLE IF NOT EXISTS `mydb`.`preview` (
  `father_id` INT NOT NULL,
  `preview_image` VARCHAR(128) NULL,
  INDEX `father_idx` (`father_id` ASC) VISIBLE,
  CONSTRAINT `father`
    FOREIGN KEY (`father_id`)
    REFERENCES `mydb`.`commodity` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_id` INT NOT NULL,
  `order_buyer` INT NOT NULL,
  `order_seller` INT NOT NULL,
  `order_num` INT NOT NULL,
  `order_price` INT NOT NULL,
  `order_address` VARCHAR(128) NOT NULL,
  `order_item` INT NOT NULL,
  `order_state` ENUM('发货', '确认收货', '退货') NOT NULL,
  `order_time` DATETIME NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `buyer_idx` (`order_buyer` ASC) VISIBLE,
  INDEX `seller_idx` (`order_seller` ASC) VISIBLE,
  INDEX `item_idx` (`order_item` ASC) VISIBLE,
  CONSTRAINT `buyer`
    FOREIGN KEY (`order_buyer`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `seller`
    FOREIGN KEY (`order_seller`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item`
    FOREIGN KEY (`order_item`)
    REFERENCES `mydb`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `com_id` INT NOT NULL,
  `com_content` VARCHAR(128) NULL,
  `com_time` DATETIME NULL,
  `com_choose` ENUM('好评', '中评', '差评') NULL,
  `commentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`com_id`),
  CONSTRAINT `order`
    FOREIGN KEY (`com_id`)
    REFERENCES `mydb`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment_picture` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment_picture` (
  `father_id` INT NOT NULL,
  `comment_image` VARCHAR(128) NULL,
  INDEX `comment_idx` (`father_id` ASC) VISIBLE,
  CONSTRAINT `comment`
    FOREIGN KEY (`father_id`)
    REFERENCES `mydb`.`comment` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
