spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sedb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 20021203
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring_learn
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  #此配置解决swagger Failed to start bean 'documentationPluginsBootstrapper'的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # thymeleaf
  thymeleaf:
    #缓冲的配置
    cache: false
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML

# mybatis-plus配置
mybatis-plus:
  mapper-locations:
    classpath:mapper/**/*Mapper.xml,classpath:mapper/*Mapper.xml
  # Mybatis返回Map类型,单数据库字段值为空时,不显示字段问题配置,true:显示值为空的字段
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080

alipay:
  appId: 9021000122679852
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCiz0CUavPhwmxLiJcojMWjemb7Exgt3hw32aIm9VoN0tp6hSjjsk3UYsAPXAB9Kft4fCi+3LIafAU0cQ3xYFbYKyxIZpUDooLX319FVNQmFX6FUarvuSRhxUKIGyAQRXcGFQUJ64FB7k99h+32bIMJA9SoYp+LhHjuU6vnaMyGf7pL2hQXtseFVlnQyhqmUoVzijtv3I4gqw+XDqh7otGmRzybf2nLmcAkVt/7DR1KFFknDAuz9WhS9NxmjcPlIEuk8p++S3EIVjDweXsGDg/toaa130xrgoBsngs+bkmJS3+9iqvT2btvNazgqY1iCd9NyD75Wy1QiIDctdccgeHVAgMBAAECggEAYxV4+xqgNFxL5ihJvk72FUjwFYuIYpnTWJYl3knhtZoGhxw1R2YDgedbdb2LOqFrPudpMMdFyWKDFGhdkPINyF92AtYTiHPF57U02RAIUOkx59dNDboCj1Iq7IR9ngl4p4XxXBkswEBVtlMcmqVtlfXz3UqwSIulwX3AmAQqvQtUV/zZZ/fUCcEQnxU0cGld2WvE4wT/b3mdBAxgXruLBTpjRBSW/T0LOeyZ8KhUvV/4skWNuiIzqk/UQ7n036dJZYAQJDPPxFwfNYNkulp00CmkJzBLec8RncSVc7BA0fDbDWeGMdUPUocmdsnzqkUSQ1tgP5t4D1KIe+ro82ReQQKBgQDUZKC2H+AZlhT3qjKq/SmYdPYoMYNFFqqqhs3rmHP3srS82+KzO+6rN73aalZ7+Bk3SusN8BoM6SKDRCxcv/XMEBnl3OGa3W6EKXJUDMImnYcdl1N3TrvB0DMsZoIiL40hnaPQ8OqVM8krYBIN77MCa928pigiJIk/JqyM//43xQKBgQDEPISGTYekfuf40QqFqMaoVm4j4AfEne8JP+uTOyEUNpWvkcJ48fXT+4WRer9qGqsqD6RLJ4RCjSiTjtNDLb1y0qqKjJS+gGzXYQqQuC4dqGfjh97C01iC5rQPBmgkYk0vSZlIv7OfpW81RU7r5ddP2NleMHBZMieubIeWFAiS0QKBgDwAGW6Z3qMbxNyaVin7zs5k7E06f4z69EesQWv263vkHi7kJ0ze93OjEZ0sQTZQRj9aiMCtPY68JaXTkny5NeTp/4byOUGYoGnxk3yvBgIGqm7vmwKvWVdNS8eVRdoGeOYwNGEIThzMPl5ki3Uoa/eZJVDv15Kdo7AVatWCU/zJAoGAfJwxS1dQGxS7GTUlCVrzS1IW/pD0XdYsRCNi5EtX5g4DX0mfxE1hXQsK9iaMBkSJDFyCZ3bgdaJNceXwIWiaNJ+xy+kZSx8h/mKQ4vUR06Ns1P8iZXTvb7AwBpp65x/FA5Io1BlnZqkWxS0NwJ5i60E4RqdbsEg5CnnAX3y5NQECgYB3WE9RLkJQkECIiUHTXcN6RF8VanUL7IgpZy37Ayng235Qp+G8LG4JhZIYCy/3tK/DcJJcrmQlfvI7dVX55+KLpbTa0Oa9P9laSwCgb8O9WhuzVTwOU7KnCPcvpV9A7NpgvZ6vGqX7LnreuH1yT9xSsXGxNFJB7X3MtovSYXLqCQ==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApwXQ3PtdaQwEqgdJL2320nDWBwjT/mPY939awPfzMCxiCgwGwqBvr013um+h3W6ZuD/c1uyV/tLQalDgew9ez5GAl0rbwxbZbcmj1xx+iAXnRBoU6qTqYgU/06sOZTnYaXDvkBslXa0Ck5LVQLyUbVmCavXFPxEgeVXTrN0+wqs1qCPZvmcn/JvwZUbtFdqNyJHHDIybhLNhXX+Wnu4wmP2fSQN0RsmrjhkACKklpuXH1z/DlmzuJIx35KkfyiC6SkZo7VTOOsP34p3gZ7RvaxWILnVt5hf+z1Q8OzQ523gWNpRgpGAUZ8eGop/CmjnudhvewNwaAvZt/JZDCPOROQIDAQAB
  notifyUrl: http://ek4hke.natappfree.cc/alipay/notify
