server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sedb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 20021203
    driver-class-name: com.mysql.cj.jdbc.Driver

